### ISSUE TITLE
[Insalltion Instructions] What is the suggest process to install / build / use `todoctor`?

### ISSUE THREAD

**Issue by Olshansk** [azat-io/todoctor#5]
What is the recommended installation process?

1. I've tried `pnpm`, `npm` and `yarn` but ended up hitting different errors with each one.
   - Let me know if I should upload the errors here for triage / debugging

2. I noticed that the expectation is to use prebuild binaries (see https://github.com/azat-io/todoctor/commit/2fbdaf1) but:
   - The `bin` directory is empty: https://github.com/azat-io/todoctor/tree/main/bin
   - The release page only contains the zipped source code: https://github.com/azat-io/todoctor/releases

I'm happy to provide more details or keep debugging, but decided to pause after having spent > 30 minutes on it.

**Comment by moltar** [comment]
It's no longer working for me either:

```
❯ npx -y todoctor@latest
Failed to find binary for @todoctor/darwin-arm64
Error: Cannot find module '@todoctor/darwin-arm64/todoctor'
Require stack:
- /Users/foo/.npm/_npx/c4447939af4b1f67/node_modules/todoctor/bin/todoctor.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function.resolve (node:internal/modules/helpers:146:19)
    at file:///Users/foo/.npm/_npx/c4447939af4b1f67/node_modules/todoctor/bin/todoctor.js:24:24
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/foo/.npm/_npx/c4447939af4b1f67/node_modules/todoctor/bin/todoctor.js'
  ]
}
```

**Comment by moltar** [comment]
Ok, the breakage occurs on `1.3.0`, works fine on `1.2.0`.

Works:

```sh
npx -y todoctor@1.2.0
```

Fails:

```sh
npx -y todoctor@1.3.0
```

**Comment by azat-io** [comment]
Thank you for your issue! Please try again.

Problem was fixed in [v1.3.5](https://github.com/azat-io/todoctor/releases/tag/v1.3.5).
